In [1]:
import numpy as np
import h5py
import os

In [23]:
filename = '/disks/cosmodm/vdvuurst/data/TEST.h5'
with h5py.File(filename, "w") as f:
    dset_test = f.create_dataset("radial_distances", (100,), dtype=np.float32, compression="gzip")

    counter = 0
    for i in range(10):
        print(counter)
        dset_test[counter:counter+10] = np.random.randint(10)
        counter += 10
    
    f.flush()

with h5py.File(filename,'r') as f:
    test = f['radial_distances'][:]

test


0
10
20
30
40
50
60
70
80
90


array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
      dtype=float32)

In [44]:
from TWOHALO import _make_mass_mask

with h5py.File('/net/hypernova/data2/FLAMINGO/L1000N1800/HYDRO_FIDUCIAL/SOAP-HBT/halo_properties_0077.hdf5', "r") as handle:
    FOFMass = handle["InputHalos/FOF/Masses"][:]
    HaloCatalogueIndex = handle["InputHalos/HaloCatalogueIndex"][:]

prim_mask = _make_mass_mask(FOFMass, 10**3.5, 10**4)
sec_mask = _make_mass_mask(FOFMass, 10**3,10**4.5)

def mask(x,i):
    return x != i

prim_ID = HaloCatalogueIndex[prim_mask]
sec_ID = HaloCatalogueIndex[sec_mask][:,np.newaxis]



In [55]:
x = 1 if False else 2
x

2

In [52]:
prim = (13.5,14)
sec = (13,15)

prim_is_subset = (sec[0] <= prim[0]) & (sec[1] >= prim[1]) 
prim_is_subset

True

In [48]:
%%timeit 

self_selection_masks = np.apply_along_axis(mask, 1, sec_ID, prim_ID)

5.84 s ± 174 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [47]:
%%timeit
for prim_id in prim_ID:
    self_selection_mask = mask(sec_ID, prim_id)


3.28 s ± 173 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [41]:
# test = np.array([np.arange(10) for _ in range(10)]).T
test = np.arange(10)[:,np.newaxis]
print(test)

def mask(x,i):
    return x != i

np.apply_along_axis(mask, 1, test, np.arange(10))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]])

In [13]:
test = [[1,1,1],[-1,-1,-1],[-1,-1,-1]]
test1 = np.linalg.norm([[-1,1,1],[1,1,1],[-1,-1,-1]],axis=1)

new = test / test1[:,np.newaxis]
print(new)

yeet = [[2,3,4],[5,1,2],[-5,-2,3]]
print(np.linalg.norm(yeet,axis=1))
np.einsum('ij,ij->i', yeet, new) 

[[ 0.57735027  0.57735027  0.57735027]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027]]
[5.38516481 5.47722558 6.164414  ]


array([ 5.19615242, -4.61880215,  2.30940108])

In [10]:
os.path.join(os.getcwd(),'/data/TEST.hdf5')

'/data/TEST.hdf5'

In [25]:
names = ['foo', 'bar']
formats = ['i4', 'i4']

dtype = np.dtype({'names': names, 'formats': formats})

data = np.array([(1, 2), (3, 4)], dtype=dtype)
print(data['foo'])

[1 3]


In [ ]:
with h5py.File('/net/hypernova/data2/FLAMINGO/L1000N1800/HYDRO_FIDUCIAL/SOAP-HBT/halo_properties_0077.hdf5', "r") as handle:
    FOFMass = handle["InputHalos/FOF/Masses"][:]
    HaloCatalogueIndex = handle["InputHalos/HaloCatalogueIndex"][:]
    COM = handle["ExclusiveSphere/100kpc/CentreOfMass"][:]

mask1 = FOFMass > 1e4
mask2 = FOFMass > 1e5

mask1.sum(), mask2.sum()

(np.int64(15580), np.int64(219))

In [ ]:
primary_IDS = HaloCatalogueIndex[mask1]
secondary_IDS = HaloCatalogueIndex[mask2]


# np.meshgrid(primary_IDS, secondary_IDS)
from itertools import combinations


{np.int64(13),
 np.int64(477346),
 np.int64(477709),
 np.int64(748905),
 np.int64(749019),
 np.int64(749025),
 np.int64(1039297),
 np.int64(1285147),
 np.int64(1773646),
 np.int64(1813398),
 np.int64(1813561),
 np.int64(1813642),
 np.int64(2087362),
 np.int64(2343519),
 np.int64(2344154),
 np.int64(2344983),
 np.int64(2345152),
 np.int64(2609359),
 np.int64(2861583),
 np.int64(2861673),
 np.int64(3104514),
 np.int64(3104524),
 np.int64(3104534),
 np.int64(3591644),
 np.int64(3879298),
 np.int64(4075851),
 np.int64(4406072),
 np.int64(4406202),
 np.int64(4406527),
 np.int64(4674230),
 np.int64(4675235),
 np.int64(4882084),
 np.int64(4934616),
 np.int64(4934747),
 np.int64(4935461),
 np.int64(4935825),
 np.int64(4937503),
 np.int64(5103543),
 np.int64(5178227),
 np.int64(5412572),
 np.int64(5645606),
 np.int64(5645957),
 np.int64(5646080),
 np.int64(5647883),
 np.int64(5650942),
 np.int64(5862835),
 np.int64(5919397),
 np.int64(5937219),
 np.int64(6037009),
 np.int64(6151302),
 np.int64(

In [ ]:
%%timeit
test = np.ones((1000))
new = np.zeros((1000,500))
for i in range(500):
    new[:,i] = test

# prims = np.arange(0,1,0.1)
# new - prims[:,np.newaxis]

713 μs ± 4.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
# %%timeit
test = np.ones((10,3))
# data = test[np.newaxis,:] - np.zeros(5)[:,np.newaxis,:]
# data
comp = (test[np.newaxis,:] - np.zeros((5,3))[:,np.newaxis,:])

np.linalg.norm(comp,axis=2)

(5, 10)

In [152]:
test = np.ones((10,10))
masks = np.zeros((10,10), dtype=bool)
masks += np.diag(np.ones(10,dtype=bool))
test[masks] = 0
test

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [ ]:

%%timeit
test = np.ones(1000)
data = np.column_stack([test for _ in range(500)])


841 μs ± 3.51 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
data = np.arange(100)
print(data)
path = '/disks/cosmodm/vdvuurst/data'
with h5py.File(os.path.join(path,'TEST.hdf5'), "w") as f:
    dset_radial = f.create_dataset("radial_distances", (100,99), dtype=np.float32, compression="gzip")

    for i in range(100):
        dset_radial[i,:] = i - data[data != i]
    
    f.flush()


with h5py.File(os.path.join(path,'TEST.hdf5'), "r") as f:
    dset_radial = f["radial_distances"][:]
    print(dset_radial[-1,:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[99. 98. 97. 96. 95. 94. 93. 92. 91. 90. 89. 88. 87. 86. 85. 84. 83. 82.
 81. 80. 79. 78. 77. 76. 75. 74. 73. 72. 71. 70. 69. 68. 67. 66. 65. 64.
 63. 62. 61. 60. 59. 58. 57. 56. 55. 54. 53. 52. 51. 50. 49. 48. 47. 46.
 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32. 31. 30. 29. 28.
 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.
  9.  8.  7.  6.  5.  4.  3.  2.  1.]
