In [91]:
import sys
if '/disks/cosmodm/vdvuurst' not in sys.path:
    sys.path.append('/disks/cosmodm/vdvuurst')

import numpy as np
import h5py
from matplotlib import pyplot as plt
import os
from importlib import reload
import json
import ONEHALO
from tqdm import tqdm
from functions import modified_logspace, BIC
from onehalo_plotter import *
from functional_forms import *
format_plot()

In [79]:
np.random.seed(42)
combi_subsample_idx = np.random.choice(len(all_combis),size = len(all_combis)//100) #1% subsample 
all_combis = np.array(all_combis, dtype=object)
combi_subsample = all_combis[combi_subsample_idx]
print(f'There are {combi_subsample.shape[0]} function combinations')

There are 74 function combinations


In [80]:
reload(ONEHALO)
jointfitter = ONEHALO.ONEHALO_joint_fitter()
jointfitter.data_dict

{'M_12.0-12.5': {'0.00-0.07': array([[  21.599976,  -31.900024,   21.700012],
         [ 160.10004 ,   15.5     ,   75.69995 ],
         [ -68.89203 ,  -83.79199 ,  -70.99194 ],
         ...,
         [ -93.      , -104.29993 ,  -48.5     ],
         [-101.29993 ,   16.199951,  -22.200012],
         [  79.900024,   27.900024,  -69.99997 ]],
        shape=(29877, 3), dtype=float32),
  '0.07-0.14': array([[-106.29999 , -346.89996 , -125.5     ],
         [ -81.80005 , -159.70007 ,  -37.5     ],
         [ 264.59998 ,   49.900024,  158.90002 ],
         ...,
         [-197.39996 ,  263.59998 , -167.      ],
         [ -55.30005 ,   61.80005 ,  133.40002 ],
         [-190.39996 ,   39.900024,   65.      ]],
        shape=(37057, 3), dtype=float32),
  '0.14-0.22': array([[ 219.39996  ,   16.       ,   98.89996  ],
         [ 118.20001  ,  127.80005  ,   24.299927 ],
         [-207.29999  ,   12.200073 ,  -34.200012 ],
         ...,
         [ -87.70001  ,  -43.80005  ,  -74.69995  ],
      

In [81]:
combi_subsample[0]

array([[<function inverse_func at 0x7f8a2f369760>,
        (<function exponential_func at 0x7f8a2f3694e0>, <function exponential_func at 0x7f8a2f3694e0>)],
       [<function poly_4_func at 0x7f8a2f3698a0>,
        (<function linear_func at 0x7f8a2f3693a0>, <function linear_func at 0x7f8a2f3693a0>, <function linear_func at 0x7f8a2f3693a0>, <function poly_3_func at 0x7f8a2f369800>, <function exponential_func at 0x7f8a2f3694e0>)],
       [<function parabola_func at 0x7f8a2f369440>,
        (<function linear_func at 0x7f8a2f3693a0>, <function linear_func at 0x7f8a2f3693a0>, <function linear_func at 0x7f8a2f3693a0>)]],
      dtype=object)

In [102]:
nr, nm = jointfitter.fit_to_data(combi_subsample[0])
print(nr)
print(nm)
print()
nparams = sum(flatten(nm))

mbin = 12.25
rbin = 0.035

np.random.seed(42)
params = np.random.randint(-100,100,size = nparams)
print(params)
print()
# lambda_n, sigma1_n, sigma2_n = nm

double_gauss_params = []
q = 0
for i,param_n in enumerate(nm):
    param_r_func, param_m_funcs = combi_subsample[0][i]
    parameters_for_r_func = []
    for j,npi in enumerate(param_n):
        ps = params[q:q+npi]
        parameters_for_r_func.append(param_m_funcs[j](mbin, *ps))
        print(ps)
        q += npi
    print(parameters_for_r_func)
    param_value = param_r_func(rbin, *parameters_for_r_func)
    print(param_value)
    print()
    double_gauss_params.append(param_value)

double_gauss_params

[2, 5, 3]
[[3, 3], [2, 2, 2, 4, 3], [2, 2, 2]]

[  2  79  -8 -86   6 -29  88 -80   2  21 -26 -13  16  -1   3  51  30  49
 -48 -99 -13  57 -63  29  91]

[ 2 79 -8]
[-86   6 -29]
[np.float64(-8.0), np.float64(-29.0)]
-257.57142857142856

[ 88 -80]
[ 2 21]
[-26 -13]
[16 -1  3 51]
[ 30  49 -48]
[np.float64(998.0), np.float64(45.5), np.float64(-331.5), np.float64(29349.9375), np.float64(-48.0)]
978.84517343625

[-99 -13]
[ 57 -63]
[29 91]
[np.float64(-1225.75), np.float64(635.25), np.float64(446.25)]
466.98220625



[np.float64(-257.57142857142856),
 np.float64(978.84517343625),
 np.float64(466.98220625)]